// AUTO-GENERATED - do not hand-edit. Regenerate from lucideData.ts + the
// Unicode emoji-test.txt matching pass (see icon-overhaul session notes) if
// lucideData.ts's curated list ever changes.
//
// The single catalog of every pickable CONTENT icon in the app. Each entry's
// `key` doubles as its Lucide name (lucideData.ts/LucideIcon) for the
// 'LUCIDE' render style - the SAME string is what's already stored in
// Family.tokenIcon / Award.icon / Countdown.emoji today, so this catalog
// slots in under the existing picker with zero data migration. `codepoints`
// is the matching real Unicode emoji (as lowercase hex, no leading "U+"),
// used to build this key's Noto/Twemoji/Fluent-3D asset filenames.
//
// A handful of entries (the reward-game types with no real Lucide icon)
// have no natural Lucide equivalent - those set `lucideFallback` to the
// closest available real icon instead of leaving 'LUCIDE' style blank.

export type IconSetName = 'LUCIDE' | 'NOTO' | 'TWEMOJI' | 'FLUENT_3D';
export const ICON_SETS: IconSetName[] = ['NOTO', 'TWEMOJI', 'FLUENT_3D'];
export const DEFAULT_ICON_SET: IconSetName = 'NOTO';

export interface CatalogEntry {
  key: string;
  label: string;
  keywords: string[];
  category: string;
  codepoints: string[];
  lucideFallback?: string; // only set when `key` itself isn't a real Lucide icon name
}

export const ICON_CATALOG: CatalogEntry[] = [
  { key: 'trophy', label: 'Trophy', keywords: ['award', 'win', 'winner', 'champion', 'cup'], category: 'Celebration, awards, achievement', codepoints: ['1f3c6'] },
  { key: 'medal', label: 'Medal', keywords: ['award', 'sports', 'first', 'second', 'third'], category: 'Celebration, awards, achievement', codepoints: ['1f3c5'] },
  { key: 'award', label: 'Award badge', keywords: ['ribbon', 'honor'], category: 'Celebration, awards, achievement', codepoints: ['1f380'] },
  { key: 'ribbon', label: 'Ribbon', keywords: ['award', 'reminder'], category: 'Celebration, awards, achievement', codepoints: ['1f380'] },
  { key: 'crown', label: 'Crown', keywords: ['king', 'queen', 'royal', 'best'], category: 'Celebration, awards, achievement', codepoints: ['1f451'] },
  { key: 'star', label: 'Star', keywords: ['favorite', 'good'], category: 'Celebration, awards, achievement', codepoints: ['2b50'] },
  { key: 'sparkle', label: 'Sparkle', keywords: ['shine', 'magic'], category: 'Celebration, awards, achievement', codepoints: ['2747', 'fe0f'] },
  { key: 'sparkles', label: 'Sparkles', keywords: ['shine', 'magic', 'clean', 'glow'], category: 'Celebration, awards, achievement', codepoints: ['2728'] },
  { key: 'flame', label: 'Flame', keywords: ['fire', 'hot', 'streak', 'lit'], category: 'Celebration, awards, achievement', codepoints: ['1f525'] },
  { key: 'zap', label: 'Lightning bolt', keywords: ['power', 'fast', 'energy', 'hero', 'superhero'], category: 'Celebration, awards, achievement', codepoints: ['26a1'] },
  { key: 'dumbbell', label: 'Dumbbell', keywords: ['muscle', 'strong', 'strength', 'flex', 'exercise'], category: 'Celebration, awards, achievement', codepoints: ['1f4aa'] },
  { key: 'thumbs-up', label: 'Thumbs up', keywords: ['good', 'yes', 'like'], category: 'Celebration, awards, achievement', codepoints: ['1f44d'] },
  { key: 'hand', label: 'Hand', keywords: ['clap', 'high five'], category: 'Celebration, awards, achievement', codepoints: ['270b'] },
  { key: 'handshake', label: 'Handshake', keywords: ['deal', 'team'], category: 'Celebration, awards, achievement', codepoints: ['1f91d'] },
  { key: 'heart', label: 'Heart', keywords: ['love'], category: 'Celebration, awards, achievement', codepoints: ['2764', 'fe0f'] },
  { key: 'heart-handshake', label: 'Heart handshake', keywords: ['love', 'team', 'kind'], category: 'Celebration, awards, achievement', codepoints: ['1f91d'] },
  { key: 'party-popper', label: 'Party popper', keywords: ['celebrate', 'confetti', 'party'], category: 'Celebration, awards, achievement', codepoints: ['1f389'] },
  { key: 'gift', label: 'Gift', keywords: ['present', 'birthday', 'prize'], category: 'Celebration, awards, achievement', codepoints: ['1f381'] },
  { key: 'rocket', label: 'Rocket', keywords: ['launch', 'space', 'fast'], category: 'Celebration, awards, achievement', codepoints: ['1f680'] },
  { key: 'rainbow', label: 'Rainbow', keywords: ['colorful', 'pride'], category: 'Celebration, awards, achievement', codepoints: ['1f308'] },
  { key: 'target', label: 'Target', keywords: ['dart', 'goal', 'bullseye'], category: 'Celebration, awards, achievement', codepoints: ['1f3af'] },
  { key: 'percent', label: 'Percent', keywords: ['100', 'perfect', 'score'], category: 'Celebration, awards, achievement', codepoints: ['1f4af'] },
  { key: 'check', label: 'Check mark', keywords: ['done', 'complete', 'yes'], category: 'Celebration, awards, achievement', codepoints: ['2714', 'fe0f'] },
  { key: 'check-check', label: 'Double check', keywords: ['done', 'complete'], category: 'Celebration, awards, achievement', codepoints: ['2705'] },
  { key: 'check-circle', label: 'Check circle', keywords: ['done', 'complete', 'yes'], category: 'Celebration, awards, achievement', codepoints: ['2705'] },
  { key: 'check-square', label: 'Check box', keywords: ['done', 'complete'], category: 'Celebration, awards, achievement', codepoints: ['2611', 'fe0f'] },
  { key: 'badge-check', label: 'Badge check', keywords: ['verified', 'award', 'good'], category: 'Celebration, awards, achievement', codepoints: ['2714', 'fe0f'] },
  { key: 'diamond', label: 'Diamond', keywords: ['gem', 'prize', 'token'], category: 'Celebration, awards, achievement', codepoints: ['1f48e'] },
  { key: 'smile', label: 'Smile', keywords: ['happy', 'grin'], category: 'Emotion / people', codepoints: ['1f642'] },
  { key: 'smile-plus', label: 'Big smile', keywords: ['happy', 'excited'], category: 'Emotion / people', codepoints: ['1f60a'] },
  { key: 'laugh', label: 'Laugh', keywords: ['lol', 'happy', 'joy'], category: 'Emotion / people', codepoints: ['1f923'] },
  { key: 'angry', label: 'Angry', keywords: ['mad'], category: 'Emotion / people', codepoints: ['1f620'] },
  { key: 'frown', label: 'Frown', keywords: ['sad'], category: 'Emotion / people', codepoints: ['1f641'] },
  { key: 'meh', label: 'Meh', keywords: ['neutral', 'unsure'], category: 'Emotion / people', codepoints: ['1f610'] },
  { key: 'baby', label: 'Baby', keywords: ['infant'], category: 'Emotion / people', codepoints: ['1f476'] },
  { key: 'user', label: 'Person', keywords: ['adult'], category: 'Emotion / people', codepoints: ['1f464'] },
  { key: 'user-round', label: 'Person', keywords: ['adult'], category: 'Emotion / people', codepoints: ['1f464'] },
  { key: 'users', label: 'People', keywords: ['family', 'group', 'team'], category: 'Emotion / people', codepoints: ['1f465'] },
  { key: 'graduation-cap', label: 'Graduation cap', keywords: ['school', 'study', 'homework'], category: 'Emotion / people', codepoints: ['1f393'] },
  { key: 'ghost', label: 'Ghost', keywords: ['spooky', 'halloween'], category: 'Emotion / people', codepoints: ['1f47b'] },
  { key: 'skull', label: 'Skull', keywords: ['spooky', 'halloween'], category: 'Emotion / people', codepoints: ['1f480'] },
  { key: 'dog', label: 'Dog', keywords: ['puppy', 'pet'], category: 'Animals / nature', codepoints: ['1f415'] },
  { key: 'cat', label: 'Cat', keywords: ['kitten', 'pet'], category: 'Animals / nature', codepoints: ['1f408'] },
  { key: 'rabbit', label: 'Rabbit', keywords: ['bunny', 'pet'], category: 'Animals / nature', codepoints: ['1f407'] },
  { key: 'bird', label: 'Bird', keywords: ['pet'], category: 'Animals / nature', codepoints: ['1f426'] },
  { key: 'feather', label: 'Feather', keywords: ['bird', 'duck', 'light'], category: 'Animals / nature', codepoints: ['1fab6'] },
  { key: 'fish', label: 'Fish', keywords: ['pet', 'aquarium'], category: 'Animals / nature', codepoints: ['1f41f'] },
  { key: 'bug', label: 'Bug', keywords: ['insect', 'bee'], category: 'Animals / nature', codepoints: ['1f41b'] },
  { key: 'turtle', label: 'Turtle', keywords: ['pet', 'slow'], category: 'Animals / nature', codepoints: ['1f422'] },
  { key: 'snail', label: 'Snail', keywords: ['slow'], category: 'Animals / nature', codepoints: ['1f40c'] },
  { key: 'squirrel', label: 'Squirrel', keywords: [], category: 'Animals / nature', codepoints: ['1f43f', 'fe0f'] },
  { key: 'paw-print', label: 'Paw print', keywords: ['pet', 'animal'], category: 'Animals / nature', codepoints: ['1f43e'] },
  { key: 'trees', label: 'Trees', keywords: ['nature', 'forest'], category: 'Animals / nature', codepoints: ['1f333'] },
  { key: 'flower', label: 'Flower', keywords: ['plant', 'spring'], category: 'Animals / nature', codepoints: ['1f337'] },
  { key: 'flower-2', label: 'Flower', keywords: ['plant', 'spring', 'blossom'], category: 'Animals / nature', codepoints: ['1f33c'] },
  { key: 'sprout', label: 'Sprout', keywords: ['plant', 'grow', 'new', 'seedling'], category: 'Animals / nature', codepoints: ['1f331'] },
  { key: 'leaf', label: 'Leaf', keywords: ['nature', 'plant', 'autumn'], category: 'Animals / nature', codepoints: ['1f343'] },
  { key: 'sun', label: 'Sun', keywords: ['sunny', 'weather'], category: 'Animals / nature', codepoints: ['2600', 'fe0f'] },
  { key: 'sunrise', label: 'Sunrise', keywords: ['morning', 'weather'], category: 'Animals / nature', codepoints: ['1f305'] },
  { key: 'sunset', label: 'Sunset', keywords: ['evening', 'weather'], category: 'Animals / nature', codepoints: ['1f307'] },
  { key: 'cloud', label: 'Cloud', keywords: ['weather'], category: 'Animals / nature', codepoints: ['2601', 'fe0f'] },
  { key: 'cloud-sun', label: 'Partly cloudy', keywords: ['weather'], category: 'Animals / nature', codepoints: ['26c5'] },
  { key: 'cloud-rain', label: 'Rain', keywords: ['weather'], category: 'Animals / nature', codepoints: ['1f327', 'fe0f'] },
  { key: 'cloud-lightning', label: 'Thunderstorm', keywords: ['weather', 'storm'], category: 'Animals / nature', codepoints: ['1f329', 'fe0f'] },
  { key: 'snowflake', label: 'Snowflake', keywords: ['snow', 'winter', 'weather'], category: 'Animals / nature', codepoints: ['2744', 'fe0f'] },
  { key: 'tornado', label: 'Tornado', keywords: ['weather', 'storm'], category: 'Animals / nature', codepoints: ['1f32a', 'fe0f'] },
  { key: 'moon', label: 'Moon', keywords: ['night', 'sleep', 'bedtime'], category: 'Animals / nature', codepoints: ['1f315'] },
  { key: 'mountain', label: 'Mountain', keywords: ['hike', 'nature'], category: 'Animals / nature', codepoints: ['26f0', 'fe0f'] },
  { key: 'mountain-snow', label: 'Snowy mountain', keywords: ['winter', 'ski'], category: 'Animals / nature', codepoints: ['1f3d4', 'fe0f'] },
  { key: 'waves', label: 'Waves', keywords: ['ocean', 'beach', 'water'], category: 'Animals / nature', codepoints: ['1f30a'] },
  { key: 'apple', label: 'Apple', keywords: ['fruit', 'food'], category: 'Food / drink', codepoints: ['1f34e'] },
  { key: 'banana', label: 'Banana', keywords: ['fruit', 'food'], category: 'Food / drink', codepoints: ['1f34c'] },
  { key: 'cherry', label: 'Cherry', keywords: ['fruit', 'food'], category: 'Food / drink', codepoints: ['1f352'] },
  { key: 'grape', label: 'Grapes', keywords: ['fruit', 'food'], category: 'Food / drink', codepoints: ['1f347'] },
  { key: 'carrot', label: 'Carrot', keywords: ['vegetable', 'food', 'healthy'], category: 'Food / drink', codepoints: ['1f955'] },
  { key: 'pizza', label: 'Pizza', keywords: ['food', 'dinner'], category: 'Food / drink', codepoints: ['1f355'] },
  { key: 'sandwich', label: 'Sandwich', keywords: ['food', 'lunch'], category: 'Food / drink', codepoints: ['1f96a'] },
  { key: 'beef', label: 'Beef', keywords: ['meat', 'food', 'dinner'], category: 'Food / drink', codepoints: ['1f969'] },
  { key: 'drumstick', label: 'Drumstick', keywords: ['chicken', 'food', 'dinner'], category: 'Food / drink', codepoints: ['1f357'] },
  { key: 'salad', label: 'Salad', keywords: ['food', 'healthy'], category: 'Food / drink', codepoints: ['1f957'] },
  { key: 'egg', label: 'Egg', keywords: ['breakfast', 'food'], category: 'Food / drink', codepoints: ['1f95a'] },
  { key: 'croissant', label: 'Croissant', keywords: ['breakfast', 'food', 'bread'], category: 'Food / drink', codepoints: ['1f950'] },
  { key: 'cake', label: 'Cake', keywords: ['birthday', 'dessert'], category: 'Food / drink', codepoints: ['1f370'] },
  { key: 'cookie', label: 'Cookie', keywords: ['dessert', 'snack'], category: 'Food / drink', codepoints: ['1f36a'] },
  { key: 'donut', label: 'Donut', keywords: ['dessert', 'snack'], category: 'Food / drink', codepoints: ['1f369'] },
  { key: 'ice-cream-cone', label: 'Ice cream', keywords: ['dessert'], category: 'Food / drink', codepoints: ['1f366'] },
  { key: 'candy', label: 'Candy', keywords: ['sweet', 'snack', 'reward'], category: 'Food / drink', codepoints: ['1f36c'] },
  { key: 'popcorn', label: 'Popcorn', keywords: ['snack', 'movie'], category: 'Food / drink', codepoints: ['1f37f'] },
  { key: 'coffee', label: 'Coffee', keywords: ['drink'], category: 'Food / drink', codepoints: ['2615'] },
  { key: 'cup-soda', label: 'Cup with straw', keywords: ['drink', 'soda'], category: 'Food / drink', codepoints: ['1f964'] },
  { key: 'milk', label: 'Milk', keywords: ['drink'], category: 'Food / drink', codepoints: ['1f95b'] },
  { key: 'utensils', label: 'Fork and knife', keywords: ['meal', 'dinner', 'food'], category: 'Food / drink', codepoints: ['1f374'] },
  { key: 'utensils-crossed', label: 'Plate with cutlery', keywords: ['dinner', 'meal', 'food', 'dishes'], category: 'Food / drink', codepoints: ['1f37d', 'fe0f'] },
  { key: 'volleyball', label: 'Volleyball', keywords: ['sports'], category: 'Activities / sports / hobbies', codepoints: ['1f3d0'] },
  { key: 'circle-dot', label: 'Ball', keywords: ['sports', 'soccer', 'target'], category: 'Activities / sports / hobbies', codepoints: ['1f518'] },
  { key: 'bike', label: 'Bicycle', keywords: ['biking', 'sports'], category: 'Activities / sports / hobbies', codepoints: ['1f6b2'] },
  { key: 'footprints', label: 'Footprints', keywords: ['walk', 'run', 'exercise'], category: 'Activities / sports / hobbies', codepoints: ['1f463'] },
  { key: 'gamepad', label: 'Game controller', keywords: ['video game', 'gaming'], category: 'Activities / sports / hobbies', codepoints: ['1f3ae'] },
  { key: 'gamepad-2', label: 'Game controller', keywords: ['video game', 'gaming'], category: 'Activities / sports / hobbies', codepoints: ['1f3ae'] },
  { key: 'joystick', label: 'Joystick', keywords: ['gaming', 'arcade'], category: 'Activities / sports / hobbies', codepoints: ['1f579', 'fe0f'] },
  { key: 'dice-5', label: 'Dice', keywords: ['board game', 'game'], category: 'Activities / sports / hobbies', codepoints: ['1f3b2'] },
  { key: 'puzzle', label: 'Puzzle piece', keywords: ['puzzle'], category: 'Activities / sports / hobbies', codepoints: ['1f9e9'] },
  { key: 'palette', label: 'Palette', keywords: ['art', 'painting', 'draw'], category: 'Activities / sports / hobbies', codepoints: ['1f3a8'] },
  { key: 'paintbrush', label: 'Paintbrush', keywords: ['art', 'draw'], category: 'Activities / sports / hobbies', codepoints: ['1f58c', 'fe0f'] },
  { key: 'pencil', label: 'Pencil', keywords: ['write', 'draw', 'homework'], category: 'Activities / sports / hobbies', codepoints: ['270f', 'fe0f'] },
  { key: 'book-open', label: 'Open book', keywords: ['reading', 'study', 'homework', 'school'], category: 'Activities / sports / hobbies', codepoints: ['1f4d6'] },
  { key: 'book', label: 'Book', keywords: ['reading', 'study'], category: 'Activities / sports / hobbies', codepoints: ['1f4d5'] },
  { key: 'music', label: 'Musical note', keywords: ['music'], category: 'Activities / sports / hobbies', codepoints: ['1f3b5'] },
  { key: 'music-2', label: 'Musical note', keywords: ['music'], category: 'Activities / sports / hobbies', codepoints: ['1f3b5'] },
  { key: 'guitar', label: 'Guitar', keywords: ['music'], category: 'Activities / sports / hobbies', codepoints: ['1f3b8'] },
  { key: 'piano', label: 'Piano', keywords: ['music'], category: 'Activities / sports / hobbies', codepoints: ['1f3b9'] },
  { key: 'mic', label: 'Microphone', keywords: ['sing', 'music'], category: 'Activities / sports / hobbies', codepoints: ['1f3a4'] },
  { key: 'mic-2', label: 'Microphone', keywords: ['sing', 'music'], category: 'Activities / sports / hobbies', codepoints: ['1f3a4'] },
  { key: 'clapperboard', label: 'Movie clapper', keywords: ['movie', 'film'], category: 'Activities / sports / hobbies', codepoints: ['1f3ac'] },
  { key: 'drama', label: 'Theater masks', keywords: ['performing arts', 'drama'], category: 'Activities / sports / hobbies', codepoints: ['1f3ad'] },
  { key: 'camera', label: 'Camera', keywords: ['photo'], category: 'Activities / sports / hobbies', codepoints: ['1f4f7'] },
  { key: 'telescope', label: 'Telescope', keywords: ['space', 'stars', 'science'], category: 'Activities / sports / hobbies', codepoints: ['1f52d'] },
  { key: 'microscope', label: 'Microscope', keywords: ['science'], category: 'Activities / sports / hobbies', codepoints: ['1f52c'] },
  { key: 'flask-conical', label: 'Flask', keywords: ['science', 'experiment'], category: 'Activities / sports / hobbies', codepoints: ['1f9ea'] },
  { key: 'car', label: 'Car', keywords: ['drive'], category: 'Travel / places', codepoints: ['1f697'] },
  { key: 'bus', label: 'Bus', keywords: [], category: 'Travel / places', codepoints: ['1f68c'] },
  { key: 'train', label: 'Train', keywords: [], category: 'Travel / places', codepoints: ['1f686'] },
  { key: 'plane', label: 'Airplane', keywords: ['flight', 'travel'], category: 'Travel / places', codepoints: ['2708', 'fe0f'] },
  { key: 'ship', label: 'Ship', keywords: ['boat', 'travel'], category: 'Travel / places', codepoints: ['1f6a2'] },
  { key: 'map', label: 'Map', keywords: ['travel'], category: 'Travel / places', codepoints: ['1f5fa', 'fe0f'] },
  { key: 'map-pin', label: 'Map pin', keywords: ['location', 'place'], category: 'Travel / places', codepoints: ['1f4cd'] },
  { key: 'map-pinned', label: 'Pinned map', keywords: ['location', 'travel'], category: 'Travel / places', codepoints: ['1f5fa', 'fe0f'] },
  { key: 'compass', label: 'Compass', keywords: ['direction', 'location'], category: 'Travel / places', codepoints: ['1f9ed'] },
  { key: 'luggage', label: 'Luggage', keywords: ['travel', 'suitcase'], category: 'Travel / places', codepoints: ['1f9f3'] },
  { key: 'tent', label: 'Tent', keywords: ['camping'], category: 'Travel / places', codepoints: ['26fa'] },
  { key: 'umbrella', label: 'Umbrella', keywords: ['beach', 'vacation', 'rain'], category: 'Travel / places', codepoints: ['2602', 'fe0f'] },
  { key: 'globe', label: 'Globe', keywords: ['world', 'earth'], category: 'Travel / places', codepoints: ['1f30d'] },
  { key: 'home', label: 'House', keywords: ['home'], category: 'Travel / places', codepoints: ['1f3e0'] },
  { key: 'house', label: 'House', keywords: ['home'], category: 'Travel / places', codepoints: ['1f3e0'] },
  { key: 'school', label: 'School', keywords: [], category: 'Travel / places', codepoints: ['1f3eb'] },
  { key: 'hospital', label: 'Hospital', keywords: [], category: 'Travel / places', codepoints: ['1f3e5'] },
  { key: 'church', label: 'Building', keywords: ['place'], category: 'Travel / places', codepoints: ['26ea'] },
  { key: 'building', label: 'Building', keywords: [], category: 'Travel / places', codepoints: ['1f3db', 'fe0f'] },
  { key: 'building-2', label: 'Building', keywords: [], category: 'Travel / places', codepoints: ['1f3e2'] },
  { key: 'landmark', label: 'Landmark', keywords: [], category: 'Travel / places', codepoints: ['1f3db', 'fe0f'] },
  { key: 'warehouse', label: 'Warehouse', keywords: ['garage'], category: 'Travel / places', codepoints: ['1f3e0'] },
  { key: 'factory', label: 'Factory', keywords: [], category: 'Travel / places', codepoints: ['1f3ed'] },
  { key: 'broom', label: 'Broom', keywords: ['clean', 'sweep', 'chore'], category: 'Objects / house / chores', codepoints: ['1f9f9'] },
  { key: 'spray-can', label: 'Spray bottle', keywords: ['clean', 'chore', 'bucket'], category: 'Objects / house / chores', codepoints: ['1faa3'] },
  { key: 'droplet', label: 'Droplet', keywords: ['water', 'clean', 'soap', 'wash'], category: 'Objects / house / chores', codepoints: ['1f4a7'] },
  { key: 'washing-machine', label: 'Washing machine', keywords: ['laundry', 'chore'], category: 'Objects / house / chores', codepoints: ['1f9fc'] },
  { key: 'shirt', label: 'Shirt', keywords: ['clothes', 'laundry'], category: 'Objects / house / chores', codepoints: ['1f455'] },
  { key: 'trash-2', label: 'Trash can', keywords: ['garbage', 'trash', 'chore'], category: 'Objects / house / chores', codepoints: ['1f5d1', 'fe0f'] },
  { key: 'bed', label: 'Bed', keywords: ['sleep', 'bedroom', 'chore', 'bedtime'], category: 'Objects / house / chores', codepoints: ['1f6cf', 'fe0f'] },
  { key: 'sofa', label: 'Couch', keywords: ['living room'], category: 'Objects / house / chores', codepoints: ['1f6cb', 'fe0f'] },
  { key: 'shower-head', label: 'Shower', keywords: ['bathroom'], category: 'Objects / house / chores', codepoints: ['1f6bf'] },
  { key: 'toilet', label: 'Toilet', keywords: ['bathroom'], category: 'Objects / house / chores', codepoints: ['1f6bd'] },
  { key: 'brush', label: 'Brush', keywords: ['clean', 'chore', 'teeth'], category: 'Objects / house / chores', codepoints: ['1faa5'] },
  { key: 'shopping-cart', label: 'Shopping cart', keywords: ['grocery', 'shopping'], category: 'Objects / house / chores', codepoints: ['1f6d2'] },
  { key: 'shopping-basket', label: 'Shopping basket', keywords: ['grocery', 'shopping', 'laundry'], category: 'Objects / house / chores', codepoints: ['1f9fa'] },
  { key: 'shopping-bag', label: 'Shopping bag', keywords: ['store', 'shopping'], category: 'Objects / house / chores', codepoints: ['1f6cd', 'fe0f'] },
  { key: 'receipt', label: 'Receipt', keywords: ['shopping', 'list'], category: 'Objects / house / chores', codepoints: ['1f9fe'] },
  { key: 'notebook-pen', label: 'Notebook', keywords: ['note', 'write', 'list'], category: 'Objects / house / chores', codepoints: ['1f4dd'] },
  { key: 'clipboard-list', label: 'Clipboard', keywords: ['checklist', 'list', 'rules'], category: 'Objects / house / chores', codepoints: ['1f4cb'] },
  { key: 'calendar', label: 'Calendar', keywords: ['date', 'schedule'], category: 'Objects / house / chores', codepoints: ['1f4c5'] },
  { key: 'calendar-days', label: 'Calendar', keywords: ['schedule', 'date'], category: 'Objects / house / chores', codepoints: ['1f4c6'] },
  { key: 'alarm-clock', label: 'Alarm clock', keywords: ['time', 'reminder'], category: 'Objects / house / chores', codepoints: ['23f0'] },
  { key: 'hourglass', label: 'Hourglass', keywords: ['time', 'waiting', 'pending'], category: 'Objects / house / chores', codepoints: ['231b'] },
  { key: 'bell', label: 'Bell', keywords: ['notification', 'reminder'], category: 'Objects / house / chores', codepoints: ['1f514'] },
  { key: 'lock', label: 'Lock', keywords: ['pin', 'secure'], category: 'Objects / house / chores', codepoints: ['1f512'] },
  { key: 'key', label: 'Key', keywords: ['unlock'], category: 'Objects / house / chores', codepoints: ['1f511'] },
  { key: 'lightbulb', label: 'Light bulb', keywords: ['idea', 'lights'], category: 'Objects / house / chores', codepoints: ['1f4a1'] },
  { key: 'wrench', label: 'Wrench', keywords: ['tool', 'fix'], category: 'Objects / house / chores', codepoints: ['1f527'] },
  { key: 'hammer', label: 'Hammer', keywords: ['tool', 'fix'], category: 'Objects / house / chores', codepoints: ['1f528'] },
  { key: 'toolbox', label: 'Toolbox', keywords: ['tools'], category: 'Objects / house / chores', codepoints: ['1f9f0'] },
  { key: 'package', label: 'Package', keywords: ['box', 'delivery'], category: 'Objects / house / chores', codepoints: ['1f4e6'] },
  { key: 'package-2', label: 'Package', keywords: ['box', 'delivery'], category: 'Objects / house / chores', codepoints: ['1f4e6'] },
  { key: 'ruler', label: 'Ruler', keywords: ['measure', 'tool'], category: 'Objects / house / chores', codepoints: ['1f4cf'] },
  { key: 'calculator', label: 'Calculator', keywords: ['math'], category: 'Objects / house / chores', codepoints: ['1f9ee'] },
  { key: 'tv', label: 'TV', keywords: ['screen', 'watch'], category: 'Objects / house / chores', codepoints: ['1f4fa'] },
  { key: 'watch', label: 'Watch', keywords: ['time'], category: 'Objects / house / chores', codepoints: ['231a'] },
  { key: 'smartphone', label: 'Phone', keywords: ['device'], category: 'Objects / house / chores', codepoints: ['1f4f1'] },
  { key: 'laptop', label: 'Laptop', keywords: ['computer'], category: 'Objects / house / chores', codepoints: ['1f4bb'] },
  { key: 'headphones', label: 'Headphones', keywords: ['music', 'listen'], category: 'Objects / house / chores', codepoints: ['1f3a7'] },
  { key: 'coins', label: 'Coins', keywords: ['coin', 'token', 'money'], category: 'Money / rewards / store', codepoints: ['1fa99'] },
  { key: 'banknote', label: 'Banknote', keywords: ['money', 'cash'], category: 'Money / rewards / store', codepoints: ['1f4b5'] },
  { key: 'wallet', label: 'Wallet', keywords: ['money', 'token'], category: 'Money / rewards / store', codepoints: ['1f45b'] },
  { key: 'gem', label: 'Gem', keywords: ['diamond', 'token', 'prize'], category: 'Money / rewards / store', codepoints: ['1f48e'] },
  { key: 'ticket', label: 'Ticket', keywords: ['token', 'event'], category: 'Money / rewards / store', codepoints: ['1f3ab'] },
  { key: 'tickets', label: 'Tickets', keywords: ['event', 'token'], category: 'Money / rewards / store', codepoints: ['1f39f', 'fe0f'] },
  { key: 'ferris-wheel', label: 'Ferris wheel', keywords: ['wheel', 'carnival', 'fun'], category: 'Money / rewards / store', codepoints: ['1f3a1'] },
  { key: 'alert-triangle', label: 'Warning', keywords: ['alert', 'caution'], category: 'Symbols', codepoints: ['26a0', 'fe0f'] },
  { key: 'help-circle', label: 'Question mark', keywords: ['unknown', 'help'], category: 'Symbols', codepoints: ['2753'] },
  { key: 'octagon-alert', label: 'Stop sign', keywords: ['alert', 'important'], category: 'Symbols', codepoints: ['1f6d1'] },
  { key: 'ban', label: 'No entry', keywords: ['forbidden', 'stop'], category: 'Symbols', codepoints: ['26d4'] },
  { key: 'recycle', label: 'Recycle', keywords: ['recycling'], category: 'Symbols', codepoints: ['267b', 'fe0f'] },
  { key: 'circle', label: 'Circle', keywords: ['shape'], category: 'Symbols', codepoints: ['26aa'] },
  { key: 'activity', label: 'Activity', keywords: ['pulse', 'health'], category: 'Symbols', codepoints: ['1f4aa'] },
  { key: 'fan', label: 'Fan', keywords: ['cool', 'air'], category: 'Symbols', codepoints: ['1faad'] },
  { key: 'slot-machine', label: 'Slot machine', keywords: ['slot machine', 'casino', 'gambling', 'reels'], category: 'Reward games', codepoints: ['1f3b0'], lucideFallback: 'joystick' },
  { key: 'plinko-ball', label: 'Plinko ball', keywords: ['plinko', 'ball', 'drop', 'peg'], category: 'Reward games', codepoints: ['26aa'], lucideFallback: 'circle' },
];

// Flat key list - server/src/common/icons.ts mirrors this exactly for
// validating AppIconSetting/FamilyIconSetting writes (same
// hand-kept-in-sync convention as FEATURE_TREE/SOUND_SLOTS - regenerate
// both together).
export const ICON_KEYS: string[] = ICON_CATALOG.map((e) => e.key);

export function findIcon(key: string): CatalogEntry | undefined {
  return ICON_CATALOG.find((e) => e.key === key);
}
