// Curated emoji library for IconPicker - name + keywords per entry so search
// actually finds things ("trash" -> 🗑️, "happy" -> 😀/😊/🎉, "dog" -> 🐕/🐶).
// Not the full Unicode set (thousands of entries, most never relevant to a
// family chore/reward app) - a few hundred entries covering the categories
// that actually come up here: celebration/awards, people, animals, food,
// activities/sports, travel/places, weather/nature, objects/house, symbols.
export interface EmojiEntry {
  emoji: string;
  name: string;
  keywords: string[];
}

function e(emoji: string, name: string, ...keywords: string[]): EmojiEntry {
  return { emoji, name, keywords: [name, ...keywords] };
}

export const EMOJI_LIBRARY: EmojiEntry[] = [
  // Celebration, awards, achievement
  e('🏆', 'trophy', 'award', 'win', 'winner', 'champion'),
  e('🥇', 'gold medal', 'first', 'award', 'win'),
  e('🥈', 'silver medal', 'second', 'award'),
  e('🥉', 'bronze medal', 'third', 'award'),
  e('🏅', 'medal', 'award', 'sports'),
  e('🎖️', 'military medal', 'award', 'honor'),
  e('⭐', 'star', 'favorite', 'good'),
  e('🌟', 'glowing star', 'sparkle', 'shine'),
  e('✨', 'sparkles', 'shine', 'magic', 'clean'),
  e('💫', 'dizzy', 'star', 'sparkle'),
  e('🔥', 'fire', 'hot', 'streak', 'lit'),
  e('💪', 'muscle', 'strong', 'strength', 'flex'),
  e('👏', 'clap', 'applause', 'good job'),
  e('🙌', 'raised hands', 'celebrate', 'yay', 'praise'),
  e('🤝', 'handshake', 'deal', 'team'),
  e('❤️', 'heart', 'love', 'red'),
  e('🧡', 'orange heart', 'love'),
  e('💛', 'yellow heart', 'love'),
  e('💚', 'green heart', 'love'),
  e('💙', 'blue heart', 'love'),
  e('💜', 'purple heart', 'love'),
  e('🎉', 'party popper', 'celebrate', 'confetti', 'party'),
  e('🎊', 'confetti ball', 'party', 'celebrate'),
  e('🎈', 'balloon', 'party', 'birthday'),
  e('🎁', 'gift', 'present', 'birthday', 'prize'),
  e('👑', 'crown', 'king', 'queen', 'royal', 'best'),
  e('🦸', 'superhero', 'hero', 'cape'),
  e('🦸‍♀️', 'superhero woman', 'hero'),
  e('🦸‍♂️', 'superhero man', 'hero'),
  e('🚀', 'rocket', 'launch', 'space', 'fast'),
  e('🌈', 'rainbow', 'colorful', 'pride'),
  e('🎯', 'dart', 'target', 'goal', 'bullseye'),
  e('🎗️', 'ribbon', 'award', 'reminder'),
  e('🏆', 'cup', 'trophy'),
  e('💯', '100', 'perfect', 'score'),
  e('✅', 'check mark', 'done', 'complete', 'yes'),
  e('☑️', 'check box', 'done', 'complete'),
  e('👍', 'thumbs up', 'good', 'yes', 'like'),

  // Faces / people
  e('😀', 'grinning face', 'happy', 'smile'),
  e('😃', 'smiley', 'happy', 'smile'),
  e('😄', 'grinning face big eyes', 'happy', 'laugh'),
  e('😁', 'beaming face', 'happy', 'grin'),
  e('😆', 'laughing', 'lol', 'happy'),
  e('😂', 'joy', 'lol', 'laughing', 'crying laughing'),
  e('🙂', 'slightly smiling', 'happy'),
  e('😊', 'blushing', 'happy', 'shy'),
  e('😇', 'angel', 'innocent', 'halo', 'good'),
  e('😎', 'sunglasses', 'cool'),
  e('🥳', 'party face', 'celebrate', 'birthday'),
  e('🤩', 'star struck', 'excited', 'amazed'),
  e('😍', 'heart eyes', 'love', 'crush'),
  e('😘', 'kiss', 'love'),
  e('🥰', 'smiling hearts', 'love', 'adore'),
  e('🤗', 'hugging face', 'hug'),
  e('🤔', 'thinking', 'hmm'),
  e('😴', 'sleeping', 'sleep', 'tired', 'bedtime'),
  e('😪', 'sleepy', 'tired'),
  e('🥱', 'yawning', 'tired', 'bored'),
  e('😢', 'crying', 'sad'),
  e('😭', 'sobbing', 'sad', 'crying'),
  e('😡', 'angry', 'mad'),
  e('😱', 'scared', 'shocked'),
  e('🤯', 'mind blown', 'shocked'),
  e('🥺', 'pleading face', 'please'),
  e('🙄', 'eye roll', 'annoyed'),
  e('😬', 'grimacing', 'awkward'),
  e('🤝', 'handshake', 'team', 'deal'),
  e('🙋', 'raising hand', 'volunteer'),
  e('🧑', 'person', 'adult'),
  e('👦', 'boy', 'kid', 'child'),
  e('👧', 'girl', 'kid', 'child'),
  e('👨‍👩‍👧‍👦', 'family', 'parents', 'kids'),
  e('🧒', 'child', 'kid'),
  e('👶', 'baby', 'infant'),
  e('🧓', 'older person', 'grandparent'),

  // Animals / nature
  e('🐶', 'dog face', 'puppy', 'pet'),
  e('🐕', 'dog', 'pet'),
  e('🐱', 'cat face', 'kitten', 'pet'),
  e('🐈', 'cat', 'pet'),
  e('🐰', 'rabbit face', 'bunny'),
  e('🐹', 'hamster', 'pet'),
  e('🐭', 'mouse face', 'pet'),
  e('🦊', 'fox'),
  e('🐻', 'bear'),
  e('🐼', 'panda'),
  e('🐨', 'koala'),
  e('🦁', 'lion'),
  e('🐯', 'tiger'),
  e('🐮', 'cow face'),
  e('🐷', 'pig face'),
  e('🐸', 'frog'),
  e('🐵', 'monkey face'),
  e('🐔', 'chicken'),
  e('🐧', 'penguin'),
  e('🦆', 'duck'),
  e('🦉', 'owl'),
  e('🦋', 'butterfly'),
  e('🐝', 'bee', 'insect'),
  e('🐢', 'turtle'),
  e('🐍', 'snake'),
  e('🐬', 'dolphin'),
  e('🐳', 'whale'),
  e('🐠', 'fish', 'tropical fish'),
  e('🦄', 'unicorn', 'magic'),
  e('🐾', 'paw prints', 'pet', 'animal'),
  e('🌳', 'tree', 'nature'),
  e('🌲', 'evergreen tree', 'nature', 'pine'),
  e('🌱', 'seedling', 'plant', 'grow', 'new'),
  e('🌷', 'tulip', 'flower'),
  e('🌸', 'cherry blossom', 'flower', 'spring'),
  e('🌻', 'sunflower', 'flower'),
  e('🌼', 'blossom', 'flower'),
  e('🍀', 'four leaf clover', 'luck'),
  e('🌵', 'cactus', 'plant'),
  e('🍂', 'fallen leaves', 'autumn', 'fall'),
  e('☀️', 'sun', 'sunny', 'weather'),
  e('🌤️', 'sun behind cloud', 'weather'),
  e('⛅', 'partly cloudy', 'weather'),
  e('☁️', 'cloud', 'weather'),
  e('🌧️', 'rain', 'weather'),
  e('⛈️', 'thunderstorm', 'weather', 'storm'),
  e('❄️', 'snowflake', 'snow', 'winter', 'weather'),
  e('⛄', 'snowman', 'winter'),
  e('🌙', 'crescent moon', 'night', 'sleep', 'bedtime'),
  e('🌜', 'moon face', 'night', 'sleep'),

  // Food / drink
  e('🍎', 'red apple', 'fruit', 'food'),
  e('🍌', 'banana', 'fruit', 'food'),
  e('🍉', 'watermelon', 'fruit', 'food'),
  e('🍇', 'grapes', 'fruit', 'food'),
  e('🍓', 'strawberry', 'fruit', 'food'),
  e('🍕', 'pizza', 'food', 'dinner'),
  e('🍔', 'hamburger', 'food', 'dinner'),
  e('🌮', 'taco', 'food', 'dinner'),
  e('🌯', 'burrito', 'food', 'dinner'),
  e('🍝', 'spaghetti', 'pasta', 'food', 'dinner'),
  e('🍜', 'noodles', 'ramen', 'food', 'dinner'),
  e('🍣', 'sushi', 'food', 'dinner'),
  e('🥗', 'salad', 'food', 'healthy'),
  e('🍗', 'poultry leg', 'chicken', 'food', 'dinner'),
  e('🥩', 'steak', 'meat', 'food', 'dinner'),
  e('🍞', 'bread', 'food'),
  e('🥞', 'pancakes', 'breakfast', 'food'),
  e('🍳', 'fried egg', 'breakfast', 'food'),
  e('🧇', 'waffle', 'breakfast', 'food'),
  e('🍰', 'cake', 'birthday', 'dessert'),
  e('🎂', 'birthday cake', 'birthday', 'celebrate'),
  e('🍪', 'cookie', 'dessert', 'snack'),
  e('🍩', 'donut', 'dessert', 'snack'),
  e('🍦', 'ice cream', 'dessert'),
  e('🍫', 'chocolate bar', 'dessert', 'snack'),
  e('🍬', 'candy', 'sweet', 'snack'),
  e('🍿', 'popcorn', 'snack', 'movie'),
  e('☕', 'coffee', 'drink'),
  e('🧃', 'juice box', 'drink'),
  e('🥤', 'cup with straw', 'drink', 'soda'),
  e('🍽️', 'plate with cutlery', 'dinner', 'meal', 'food'),
  e('🍴', 'fork and knife', 'meal', 'dinner'),

  // Activities / sports / hobbies
  e('⚽', 'soccer ball', 'sports', 'football'),
  e('🏀', 'basketball', 'sports'),
  e('🏈', 'football', 'sports'),
  e('⚾', 'baseball', 'sports'),
  e('🎾', 'tennis', 'sports'),
  e('🏐', 'volleyball', 'sports'),
  e('🏓', 'ping pong', 'table tennis', 'sports'),
  e('🏸', 'badminton', 'sports'),
  e('🥊', 'boxing glove', 'sports'),
  e('🚴', 'cyclist', 'biking', 'sports'),
  e('🏃', 'runner', 'running', 'exercise'),
  e('🏊', 'swimmer', 'swimming', 'sports'),
  e('🧘', 'meditation', 'yoga', 'calm'),
  e('🎮', 'video game', 'gaming', 'controller'),
  e('🕹️', 'joystick', 'gaming'),
  e('🎲', 'game die', 'dice', 'board game'),
  e('🧩', 'puzzle piece', 'puzzle'),
  e('♟️', 'chess pawn', 'chess', 'strategy'),
  e('🎨', 'palette', 'art', 'painting', 'draw'),
  e('🖌️', 'paintbrush', 'art', 'draw'),
  e('✏️', 'pencil', 'write', 'draw', 'homework'),
  e('📚', 'books', 'reading', 'study', 'homework', 'school'),
  e('📖', 'open book', 'reading', 'study'),
  e('🎵', 'musical note', 'music'),
  e('🎸', 'guitar', 'music'),
  e('🎹', 'piano', 'music'),
  e('🎤', 'microphone', 'sing', 'music'),
  e('🎬', 'movie clapper', 'movie', 'film'),
  e('🎭', 'performing arts', 'theater', 'drama'),
  e('📷', 'camera', 'photo'),
  e('🧗', 'climbing', 'sports'),
  e('🛹', 'skateboard', 'sports'),
  e('🏄', 'surfing', 'sports'),
  e('⛷️', 'skiing', 'sports', 'winter'),
  e('🏂', 'snowboarding', 'sports', 'winter'),

  // Travel / places
  e('🚗', 'car', 'drive'),
  e('🚌', 'bus'),
  e('🚲', 'bicycle', 'bike'),
  e('✈️', 'airplane', 'flight', 'travel'),
  e('🚢', 'ship', 'boat', 'travel'),
  e('🏠', 'house', 'home'),
  e('🏡', 'house with garden', 'home'),
  e('🏫', 'school'),
  e('🏥', 'hospital'),
  e('⛺', 'tent', 'camping'),
  e('🏖️', 'beach', 'vacation', 'travel'),
  e('🗺️', 'map', 'travel'),
  e('🧳', 'luggage', 'travel', 'suitcase'),
  e('🌍', 'globe', 'world', 'earth'),

  // Objects / house / chores
  e('🧹', 'broom', 'clean', 'sweep', 'chore'),
  e('🧺', 'basket', 'laundry', 'chore'),
  e('🧼', 'soap', 'clean', 'wash'),
  e('🧽', 'sponge', 'clean', 'wash'),
  e('🧴', 'lotion', 'bottle', 'wash'),
  e('🪣', 'bucket', 'clean', 'chore'),
  e('🗑️', 'trash can', 'garbage', 'trash', 'chore'),
  e('🛏️', 'bed', 'sleep', 'bedroom', 'chore', 'bedtime'),
  e('🛋️', 'couch', 'living room'),
  e('🚿', 'shower', 'bathroom'),
  e('🪥', 'toothbrush', 'teeth', 'brush', 'chore'),
  e('🧻', 'toilet paper', 'bathroom'),
  e('🍽️', 'dishes', 'plate', 'chore', 'kitchen'),
  e('🧑‍🍳', 'cooking', 'chef', 'kitchen', 'chore'),
  e('🛒', 'shopping cart', 'grocery', 'shopping'),
  e('🧾', 'receipt', 'shopping', 'list'),
  e('📝', 'memo', 'note', 'write', 'list'),
  e('📋', 'clipboard', 'checklist', 'list', 'rules'),
  e('📅', 'calendar', 'date', 'schedule'),
  e('🗓️', 'spiral calendar', 'schedule', 'date'),
  e('⏰', 'alarm clock', 'time', 'reminder'),
  e('⏳', 'hourglass', 'time', 'waiting', 'pending'),
  e('🔔', 'bell', 'notification', 'reminder'),
  e('🔒', 'locked', 'pin', 'secure'),
  e('🔑', 'key', 'unlock'),
  e('💡', 'light bulb', 'idea', 'lights'),
  e('🔧', 'wrench', 'tool', 'fix'),
  e('🧰', 'toolbox', 'tools'),
  e('📦', 'package', 'box', 'delivery'),
  e('🚗', 'garage', 'car'),
  e('🌱', 'plant', 'yard', 'garden', 'chore'),
  e('🐕', 'walk the dog', 'pet', 'chore'),
  e('🐾', 'pet care', 'chore'),

  // Money / rewards / store
  e('🪙', 'coin', 'token', 'money'),
  e('💰', 'money bag', 'money', 'token'),
  e('💎', 'gem', 'diamond', 'token', 'prize'),
  e('🎫', 'ticket', 'token', 'event'),
  e('🎟️', 'admission ticket', 'event', 'token'),
  e('🛍️', 'shopping bags', 'store', 'shopping'),
  e('🍬', 'candy reward', 'sweet', 'reward'),

  // Weather + misc symbols
  e('❗', 'exclamation', 'important', 'alert'),
  e('❓', 'question mark', 'unknown', 'help'),
  e('⚠️', 'warning', 'alert', 'caution'),
  e('🚫', 'no entry', 'forbidden', 'stop'),
  e('♻️', 'recycle', 'recycling'),
  e('📍', 'pin', 'location', 'place'),
  e('🧭', 'compass', 'direction', 'location'),
];
