// Curated Lucide icon library for IconPicker - name + keywords per entry so
// search actually finds things ("trash" -> trash-2, "happy" -> smile,
// "dog" -> dog), same shape/categories as the emoji library this replaced
// (see git history for emojiData.ts). Not the full ~2000-icon set Lucide
// ships (most never relevant to a family chore/reward app) - a curated
// couple hundred covering the categories that come up here: celebration/
// awards, people/emotion, animals/nature, food, activities/sports, travel/
// places, objects/house/chores, money/rewards, symbols.
//
// `name` is the exact Lucide icon name (kebab-case, e.g. "party-popper") -
// it's what actually gets stored (Family.tokenIcon, Award.icon,
// Countdown.emoji) and what LucideIcon/DynamicIcon resolve by. Verified
// against the installed lucide-react package's real icon list before adding
// any entry here - don't add a name without checking
// node_modules/lucide-react/dynamicIconImports.mjs (or the dist/esm/icons
// directory) first, since a typo'd/hallucinated name renders nothing.
export interface LucideEntry {
  name: string;
  label: string;
  keywords: string[];
}

function i(name: string, label: string, ...keywords: string[]): LucideEntry {
  return { name, label, keywords: [label, name, ...keywords] };
}

export const LUCIDE_LIBRARY: LucideEntry[] = [
  // Celebration, awards, achievement
  i('trophy', 'Trophy', 'award', 'win', 'winner', 'champion', 'cup'),
  i('medal', 'Medal', 'award', 'sports', 'first', 'second', 'third'),
  i('award', 'Award badge', 'ribbon', 'honor'),
  i('ribbon', 'Ribbon', 'award', 'reminder'),
  i('crown', 'Crown', 'king', 'queen', 'royal', 'best'),
  i('star', 'Star', 'favorite', 'good'),
  i('sparkle', 'Sparkle', 'shine', 'magic'),
  i('sparkles', 'Sparkles', 'shine', 'magic', 'clean', 'glow'),
  i('flame', 'Flame', 'fire', 'hot', 'streak', 'lit'),
  i('zap', 'Lightning bolt', 'power', 'fast', 'energy', 'hero', 'superhero'),
  i('dumbbell', 'Dumbbell', 'muscle', 'strong', 'strength', 'flex', 'exercise'),
  i('thumbs-up', 'Thumbs up', 'good', 'yes', 'like'),
  i('hand', 'Hand', 'clap', 'high five'),
  i('handshake', 'Handshake', 'deal', 'team'),
  i('heart', 'Heart', 'love'),
  i('heart-handshake', 'Heart handshake', 'love', 'team', 'kind'),
  i('party-popper', 'Party popper', 'celebrate', 'confetti', 'party'),
  i('gift', 'Gift', 'present', 'birthday', 'prize'),
  i('rocket', 'Rocket', 'launch', 'space', 'fast'),
  i('rainbow', 'Rainbow', 'colorful', 'pride'),
  i('target', 'Target', 'dart', 'goal', 'bullseye'),
  i('percent', 'Percent', '100', 'perfect', 'score'),
  i('check', 'Check mark', 'done', 'complete', 'yes'),
  i('check-check', 'Double check', 'done', 'complete'),
  i('check-circle', 'Check circle', 'done', 'complete', 'yes'),
  i('check-square', 'Check box', 'done', 'complete'),
  i('badge-check', 'Badge check', 'verified', 'award', 'good'),
  i('diamond', 'Diamond', 'gem', 'prize', 'token'),

  // Emotion / people
  i('smile', 'Smile', 'happy', 'grin'),
  i('smile-plus', 'Big smile', 'happy', 'excited'),
  i('laugh', 'Laugh', 'lol', 'happy', 'joy'),
  i('angry', 'Angry', 'mad'),
  i('frown', 'Frown', 'sad'),
  i('meh', 'Meh', 'neutral', 'unsure'),
  i('baby', 'Baby', 'infant'),
  i('user', 'Person', 'adult'),
  i('user-round', 'Person', 'adult'),
  i('users', 'People', 'family', 'group', 'team'),
  i('graduation-cap', 'Graduation cap', 'school', 'study', 'homework'),
  i('ghost', 'Ghost', 'spooky', 'halloween'),
  i('skull', 'Skull', 'spooky', 'halloween'),

  // Animals / nature
  i('dog', 'Dog', 'puppy', 'pet'),
  i('cat', 'Cat', 'kitten', 'pet'),
  i('rabbit', 'Rabbit', 'bunny', 'pet'),
  i('bird', 'Bird', 'pet'),
  i('feather', 'Feather', 'bird', 'duck', 'light'),
  i('fish', 'Fish', 'pet', 'aquarium'),
  i('bug', 'Bug', 'insect', 'bee'),
  i('turtle', 'Turtle', 'pet', 'slow'),
  i('snail', 'Snail', 'slow'),
  i('squirrel', 'Squirrel'),
  i('paw-print', 'Paw print', 'pet', 'animal'),
  i('trees', 'Trees', 'nature', 'forest'),
  i('flower', 'Flower', 'plant', 'spring'),
  i('flower-2', 'Flower', 'plant', 'spring', 'blossom'),
  i('sprout', 'Sprout', 'plant', 'grow', 'new', 'seedling'),
  i('leaf', 'Leaf', 'nature', 'plant', 'autumn'),
  i('sun', 'Sun', 'sunny', 'weather'),
  i('sunrise', 'Sunrise', 'morning', 'weather'),
  i('sunset', 'Sunset', 'evening', 'weather'),
  i('cloud', 'Cloud', 'weather'),
  i('cloud-sun', 'Partly cloudy', 'weather'),
  i('cloud-rain', 'Rain', 'weather'),
  i('cloud-lightning', 'Thunderstorm', 'weather', 'storm'),
  i('snowflake', 'Snowflake', 'snow', 'winter', 'weather'),
  i('tornado', 'Tornado', 'weather', 'storm'),
  i('moon', 'Moon', 'night', 'sleep', 'bedtime'),
  i('mountain', 'Mountain', 'hike', 'nature'),
  i('mountain-snow', 'Snowy mountain', 'winter', 'ski'),
  i('waves', 'Waves', 'ocean', 'beach', 'water'),

  // Food / drink
  i('apple', 'Apple', 'fruit', 'food'),
  i('banana', 'Banana', 'fruit', 'food'),
  i('cherry', 'Cherry', 'fruit', 'food'),
  i('grape', 'Grapes', 'fruit', 'food'),
  i('carrot', 'Carrot', 'vegetable', 'food', 'healthy'),
  i('pizza', 'Pizza', 'food', 'dinner'),
  i('sandwich', 'Sandwich', 'food', 'lunch'),
  i('beef', 'Beef', 'meat', 'food', 'dinner'),
  i('drumstick', 'Drumstick', 'chicken', 'food', 'dinner'),
  i('salad', 'Salad', 'food', 'healthy'),
  i('egg', 'Egg', 'breakfast', 'food'),
  i('croissant', 'Croissant', 'breakfast', 'food', 'bread'),
  i('cake', 'Cake', 'birthday', 'dessert'),
  i('cookie', 'Cookie', 'dessert', 'snack'),
  i('donut', 'Donut', 'dessert', 'snack'),
  i('ice-cream-cone', 'Ice cream', 'dessert'),
  i('candy', 'Candy', 'sweet', 'snack', 'reward'),
  i('popcorn', 'Popcorn', 'snack', 'movie'),
  i('coffee', 'Coffee', 'drink'),
  i('cup-soda', 'Cup with straw', 'drink', 'soda'),
  i('milk', 'Milk', 'drink'),
  i('utensils', 'Fork and knife', 'meal', 'dinner', 'food'),
  i('utensils-crossed', 'Plate with cutlery', 'dinner', 'meal', 'food', 'dishes'),

  // Activities / sports / hobbies
  i('volleyball', 'Volleyball', 'sports'),
  i('circle-dot', 'Ball', 'sports', 'soccer', 'target'),
  i('bike', 'Bicycle', 'biking', 'sports'),
  i('footprints', 'Footprints', 'walk', 'run', 'exercise'),
  i('gamepad', 'Game controller', 'video game', 'gaming'),
  i('gamepad-2', 'Game controller', 'video game', 'gaming'),
  i('joystick', 'Joystick', 'gaming', 'arcade'),
  i('dice-5', 'Dice', 'board game', 'game'),
  i('puzzle', 'Puzzle piece', 'puzzle'),
  i('palette', 'Palette', 'art', 'painting', 'draw'),
  i('paintbrush', 'Paintbrush', 'art', 'draw'),
  i('pencil', 'Pencil', 'write', 'draw', 'homework'),
  i('book-open', 'Open book', 'reading', 'study', 'homework', 'school'),
  i('book', 'Book', 'reading', 'study'),
  i('music', 'Musical note', 'music'),
  i('music-2', 'Musical note', 'music'),
  i('guitar', 'Guitar', 'music'),
  i('piano', 'Piano', 'music'),
  i('mic', 'Microphone', 'sing', 'music'),
  i('mic-2', 'Microphone', 'sing', 'music'),
  i('clapperboard', 'Movie clapper', 'movie', 'film'),
  i('drama', 'Theater masks', 'performing arts', 'drama'),
  i('camera', 'Camera', 'photo'),
  i('telescope', 'Telescope', 'space', 'stars', 'science'),
  i('microscope', 'Microscope', 'science'),
  i('flask-conical', 'Flask', 'science', 'experiment'),

  // Travel / places
  i('car', 'Car', 'drive'),
  i('bus', 'Bus'),
  i('train', 'Train'),
  i('plane', 'Airplane', 'flight', 'travel'),
  i('ship', 'Ship', 'boat', 'travel'),
  i('map', 'Map', 'travel'),
  i('map-pin', 'Map pin', 'location', 'place'),
  i('map-pinned', 'Pinned map', 'location', 'travel'),
  i('compass', 'Compass', 'direction', 'location'),
  i('luggage', 'Luggage', 'travel', 'suitcase'),
  i('tent', 'Tent', 'camping'),
  i('umbrella', 'Umbrella', 'beach', 'vacation', 'rain'),
  i('globe', 'Globe', 'world', 'earth'),
  i('home', 'House', 'home'),
  i('house', 'House', 'home'),
  i('school', 'School'),
  i('hospital', 'Hospital'),
  i('church', 'Building', 'place'),
  i('building', 'Building'),
  i('building-2', 'Building'),
  i('landmark', 'Landmark'),
  i('warehouse', 'Warehouse', 'garage'),
  i('factory', 'Factory'),

  // Objects / house / chores
  i('broom', 'Broom', 'clean', 'sweep', 'chore'),
  i('spray-can', 'Spray bottle', 'clean', 'chore', 'bucket'),
  i('droplet', 'Droplet', 'water', 'clean', 'soap', 'wash'),
  i('washing-machine', 'Washing machine', 'laundry', 'chore'),
  i('shirt', 'Shirt', 'clothes', 'laundry'),
  i('trash-2', 'Trash can', 'garbage', 'trash', 'chore'),
  i('bed', 'Bed', 'sleep', 'bedroom', 'chore', 'bedtime'),
  i('sofa', 'Couch', 'living room'),
  i('shower-head', 'Shower', 'bathroom'),
  i('toilet', 'Toilet', 'bathroom'),
  i('brush', 'Brush', 'clean', 'chore', 'teeth'),
  i('shopping-cart', 'Shopping cart', 'grocery', 'shopping'),
  i('shopping-basket', 'Shopping basket', 'grocery', 'shopping', 'laundry'),
  i('shopping-bag', 'Shopping bag', 'store', 'shopping'),
  i('receipt', 'Receipt', 'shopping', 'list'),
  i('notebook-pen', 'Notebook', 'note', 'write', 'list'),
  i('clipboard-list', 'Clipboard', 'checklist', 'list', 'rules'),
  i('calendar', 'Calendar', 'date', 'schedule'),
  i('calendar-days', 'Calendar', 'schedule', 'date'),
  i('alarm-clock', 'Alarm clock', 'time', 'reminder'),
  i('hourglass', 'Hourglass', 'time', 'waiting', 'pending'),
  i('bell', 'Bell', 'notification', 'reminder'),
  i('lock', 'Lock', 'pin', 'secure'),
  i('key', 'Key', 'unlock'),
  i('lightbulb', 'Light bulb', 'idea', 'lights'),
  i('wrench', 'Wrench', 'tool', 'fix'),
  i('hammer', 'Hammer', 'tool', 'fix'),
  i('toolbox', 'Toolbox', 'tools'),
  i('package', 'Package', 'box', 'delivery'),
  i('package-2', 'Package', 'box', 'delivery'),
  i('ruler', 'Ruler', 'measure', 'tool'),
  i('calculator', 'Calculator', 'math'),
  i('tv', 'TV', 'screen', 'watch'),
  i('watch', 'Watch', 'time'),
  i('smartphone', 'Phone', 'device'),
  i('laptop', 'Laptop', 'computer'),
  i('headphones', 'Headphones', 'music', 'listen'),

  // Money / rewards / store
  i('coins', 'Coins', 'coin', 'token', 'money'),
  i('banknote', 'Banknote', 'money', 'cash'),
  i('wallet', 'Wallet', 'money', 'token'),
  i('gem', 'Gem', 'diamond', 'token', 'prize'),
  i('ticket', 'Ticket', 'token', 'event'),
  i('tickets', 'Tickets', 'event', 'token'),
  i('ferris-wheel', 'Ferris wheel', 'wheel', 'carnival', 'fun'),

  // Symbols
  i('alert-triangle', 'Warning', 'alert', 'caution'),
  i('help-circle', 'Question mark', 'unknown', 'help'),
  i('octagon-alert', 'Stop sign', 'alert', 'important'),
  i('ban', 'No entry', 'forbidden', 'stop'),
  i('recycle', 'Recycle', 'recycling'),
  i('circle', 'Circle', 'shape'),
  i('activity', 'Activity', 'pulse', 'health'),
  i('fan', 'Fan', 'cool', 'air'),
];
